output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.main.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.main.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.main.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.main.kubectl_config
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.main.config_map_aws_auth
}

output "vpc_id" {
  description = "Outputting vpc_id to be used in our EKS"
  value       = module.main.vpc_id
}

output "private_subnets" {
  description = "Outputting private_subnets to be used in our EKS"
  value       = module.main.private_subnets
}

output "securitygroup_id" {
  description = "Outputting security group id"
  value       = module.main.securitygroup_id
}

output "region" {
  description = "Region selected to create all resources"
  value       = var.region
}


output "kms_arn" {
  description = "The Amazon Resource Name (ARN) of the key."
  value       = module.main.arn
}

output "kms_key_id" {
  description = "The globally unique identifier for the key."
  value       = module.main.key_id
}